config/routes.rb
App::Application.routes.draw do
  resources :media_converters

  match '/',  via: :get,  to: 'calcs#calc'
  match '/',  via: :post, to: 'calcs#exec_calc', as: :calcs

end

app/models/calc.rb
# -*- coding: utf-8 -*-
class Calc < NonActiveRecord::Base
  attr_accessor :relay_distance, :building_num, :admission_distance, :connector_num, :bandwidth,
                :relay_distance_attenuation, :bilding_num_attenuation, :connector_num_per_builing, :admission_distance_attenuation,
                :start_and_end_point_num, :start_and_end_point_num_attenuation
end

app/models/media_converter.rb
class MediaConverter < ActiveRecord::Base
  attr_accessible :bandwidth, :name, :trans_lost_from, :trans_lost_to, :code_core_num, :fiber_type,
                  :manufacturer, :price, :buying_price, :sale_price, :desc

  validates :name,              presence: true, length: {maximum: 50}
  validates :manufacturer,      presence: true
  validates :trans_lost_from,   numericality: true
  validates :trans_lost_to,     numericality: true
  validates :bandwidth,         numericality: true
  validates :fiber_type,        presence: true
  validates :code_core_num,     presence: true
  validates :price,             numericality: true, allow_blank: true
  validates :buying_price,      numericality: true, allow_blank: true
  validates :sale_price,        numericality: true, allow_blank: true

  def self.bandwidths
   [
     ["100M", 100],
     ["1G", 1000],
     ["10G", 10000],
   ]
  end
end

app/models/non_active_record/base.rb
module NonActiveRecord
  class Base
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend  ActiveModel::Naming
    
    def initialize(attributes = {})
      return if attributes.nil?
      
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end
    
    def persisted?
      false
    end
    
    def read_attribute(key)
      send(key)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calcs_controller.rb
class CalcsController < ApplicationController
  def calc
    @calc = Calc.new 

    # フォームデフォルト値を設定
    @calc.relay_distance_attenuation          = 0.5
    @calc.connector_num_per_builing           = 2
    @calc.bilding_num_attenuation             = 0.5
    @calc.admission_distance_attenuation      = 0.5
    @calc.start_and_end_point_num_attenuation = 0.5
    @calc.start_and_end_point_num             = 2
  end
 
  def exec_calc 
    @calc = Calc.new params[:calc]

    # 減衰値を計算
    @attenuation = ((@calc.relay_distance.to_f * @calc.relay_distance_attenuation.to_f) \
                 + (@calc.building_num.to_f * @calc.connector_num_per_builing.to_f * @calc.bilding_num_attenuation.to_f) \
                 + (@calc.admission_distance.to_f * @calc.admission_distance_attenuation.to_f) \
                 + (@calc.start_and_end_point_num_attenuation.to_f * @calc.connector_num.to_f * @calc.start_and_end_point_num.to_f))

    @media_converters = MediaConverter.where(["bandwidth = ? AND trans_lost_from <= ? AND trans_lost_to >= ?", @calc.bandwidth, @attenuation, @attenuation])
                                      .order("bandwidth DESC, manufacturer ASC, name ASC")
  end
end

app/controllers/media_converters_controller.rb
# -*- coding: utf-8 -*-
class MediaConvertersController < ApplicationController
  # GET /media_converters
  # GET /media_converters.json
  def index
    @media_converters = MediaConverter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @media_converters }
    end
  end

  # GET /media_converters/1
  # GET /media_converters/1.json
  def show
    @media_converter = MediaConverter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @media_converter }
    end
  end

  # GET /media_converters/new
  # GET /media_converters/new.json
  def new
    @media_converter = MediaConverter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @media_converter }
    end
  end

  # GET /media_converters/1/edit
  def edit
    @media_converter = MediaConverter.find(params[:id])
  end

  # POST /media_converters
  # POST /media_converters.json
  def create
    @media_converter = MediaConverter.new(params[:media_converter])

    respond_to do |format|
      if @media_converter.save
        format.html { redirect_to @media_converter, notice: 'メディコンマスターの登録が完了しました.' }
        format.json { render json: @media_converter, status: :created, location: @media_converter }
      else
        format.html { render action: "new" }
        format.json { render json: @media_converter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /media_converters/1
  # PUT /media_converters/1.json
  def update
    @media_converter = MediaConverter.find(params[:id])

    respond_to do |format|
      if @media_converter.update_attributes(params[:media_converter])
        format.html { redirect_to @media_converter, notice: 'メディコンマスターの更新が完了しました.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @media_converter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_converters/1
  # DELETE /media_converters/1.json
  def destroy
    @media_converter = MediaConverter.find(params[:id])
    @media_converter.destroy

    respond_to do |format|
      format.html { redirect_to media_converters_url, notice: 'メディコンマスターの削除が完了しました.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def model_column_string(model, key)
    if model.is_a?(NonActiveRecord::Base)
      i18n_namespace = "activemodel.attributes.#{model.class.to_s.classify.underscore}.#{key}"
    else
      i18n_namespace = "activerecord.attributes.#{model.class.to_s.classify.underscore}.#{key}"
    end
    I18n.t(i18n_namespace, default: nil)
  end

  def label_field(f, key, opts = {})
    opts = {
      class: "control-label",
    }.merge(opts)

    model = f.object

    f.label key, model_column_string(model, key), opts
  end
end

app/helpers/media_converters_helper.rb
module MediaConvertersHelper
  def convert_size(value)
    array = MediaConverter.bandwidths.select{|e| e[1] == value.to_i}

    return array[0][0] if array != []

    return value
  end
end

app/views/calcs/_form.html.erb
<h1 class="top-font">だーく三十郎 とっぷぺーじ</h1>
<br />

<div class="row"> 
  <div class="span8"> 
  <%= form_for(@calc,  {:html => {class: "form-inline"}}) do |f| %>
    <%= render "partials/form_error_messages", model: @calc %>

    <table class="table">
      <tr>
        <th><%= label_field f, "relay_distance" %></th>
        <th></th>
        <th><%= label_field f, "relay_distance_attenuation" %></th>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><%= f.text_field "relay_distance", style: "width:100px;" %></td>
        <td> x </td>
        <td><%= f.text_field "relay_distance_attenuation", style: "width:50px;" %></td>
        <td></td>
        <td></td>
      </tr>

      <tr>
        <th><%= label_field f, "building_num" %></th>
        <th></th>
        <th><%= label_field f, "connector_num_per_builing" %></th>
        <th></th>
        <th><%= label_field f, "bilding_num_attenuation" %></th>
      </tr>
      <tr>
        <td><%= f.text_field "building_num", style: "width:100px;" %></td>
        <td> x </td>
        <td><%= f.text_field "connector_num_per_builing", style: "width:50px;" %></td>
        <td> x </td>
        <td><%= f.text_field "bilding_num_attenuation", style: "width:50px;" %></td>
      </tr>

      <tr>
        <td><%= label_field f, "admission_distance" %></td>
        <td></td>
        <td><%= label_field f, "admission_distance_attenuation" %></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td><%= f.text_field "admission_distance", style: "width:100px;" %></td>
        <td> x </td>
        <td><%= f.text_field "admission_distance_attenuation", style: "width:50px;" %></td>
        <td></td>
        <td></td>
      </tr>

      <tr>
        <td><%= label_field f, "start_and_end_point_num" %></td>
        <td></td>
        <td><%= label_field f, "connector_num" %></td>
        <td></td>
        <td><%= label_field f, "start_and_end_point_num_attenuation" %></td>
      </tr>
      <tr>
        <td><%= f.text_field "start_and_end_point_num", style: "width:50px;" %></td>
        <td> x </td>
        <td><%= f.text_field "connector_num", style: "width:100px;" %></td>
        <td> x </td>
        <td><%= f.text_field "start_and_end_point_num_attenuation", style: "width:50px;" %></td>
      </tr>

      <tr>
        <td> <%= f.label "帯域", class: "control-label" %></td>
        <td colspan="4">
          <%= f.select("bandwidth", MediaConverter.bandwidths, {}, {class: 'form-control'})  %>
        </td>
      </tr>
   </table>
        
    <div class="actions">
      <%= f.submit "計算ッ!", class:"btn btn-primary pull-right clearfix" %>
    </div>
  <% end %>
  </div>
</div>

app/views/calcs/calc.html.erb
<%= render 'form' %>

app/views/calcs/exec_calc.html.erb
<%= render 'form' %>
<hr />

減衰値は <%= @attenuation %>dB です<br />
<br />

<% if @media_converters.size > 0 %>
  対象機器が <%= @media_converters.size %>件 見つかりました<br />
  <%= render "partials/media_converter_table", is_menu: false %>
<% else %>
  対象機器はありません
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "だーく三十郎" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Top</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "めでぃこんますた", media_converters_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="margin-top: 60px;">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <hr />
        <p>&copy; copyright yamatomo 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/media_converters/_form.html.erb
<div class="row"> 
  <div class="span6"> 
  <%= form_for(@media_converter,  {:html => { class: "form-horizontal" }}) do |f| %>
    <%= render "partials/form_error_messages", model: @media_converter %>

    <% %w(name manufacturer trans_lost_from trans_lost_to fiber_type code_core_num price buying_price sale_price ).each do |name| %>
    <div class="control-group">
      <%= label_field f, name %>
      <div class="controls"><%= f.text_field name %></div>
    </div>
    <% end %>

    <% name = "bandwidth" %>
    <div class="control-group">
      <%= label_field f, name %>
      <div class="controls"><%= f.select(name, MediaConverter.bandwidths, {}, {class: 'form-control'}) %></div>
    </div>

    <% name = "desc" %>
    <div class="control-group">
      <%= label_field f, name %>
      <div class="controls"><%= f.text_field name %></div>
    </div>
  
    <div class="actions">
      <% if mode == :new %>
      <%= f.submit "作成", class:"btn btn-primary pull-right clearfix" %>
      <% else %>
      <%= f.submit "修正", class:"btn btn-primary pull-right clearfix" %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/media_converters/edit.html.erb
<h1 class="top-font">めでぃこんますた 修正</h1>
<br />

<%= render 'form', mode: :edit %>

<%= link_to '一覧へ戻る', :back  %> <br />
<br />

app/views/media_converters/index.html.erb
<h1 class="top-font">めでぃこんますた 一覧</h1>
<br />

<a class="btn btn-primary" href="<%= url_for new_media_converter_path %>">新規登録</a> <br />
<br />

<% if @media_converters.size > 0 %>
<%= render "partials/media_converter_table", is_menu: true %>
<br />
<% else %>
データがありません
<% end %>

app/views/media_converters/new.html.erb
<h1 class="top-font">めでぃこんますた 作成</h1>
<br />

<%= render 'form', mode: :new %>

<%= link_to '一覧へ戻る', :back  %> <br />

app/views/media_converters/show.html.erb
<table class="table table-bordered">
  <% %w(name manufacturer).each do |name| %>
  <tr>
    <th><%= model_column_string @media_converter, name %></th>
    <td><%= @media_converter.send name %></td>
  </tr>
  <% end %>
  <tr>
    <th>伝送損失(dB)</th>
    <td><%= @media_converter.trans_lost_from %> ~ <%= @media_converter.trans_lost_to %></td>
  </tr>
  <% %w(fiber_type code_core_num price buying_price sale_price bandwidth desc).each do |name| %>
  <tr>
    <th><%= model_column_string @media_converter, name %></th>
    <% if ["price", "buying_price", "sale_price"].include? name %>
    <td><%= number_to_currency @media_converter.send(name), format: '%u %n', unit: '¥', precision: 0 %></td>
    <% else %>
    <td><%= @media_converter.send name %></td>
    <% end %>
  </tr>
<% end %>
</table>

<%= link_to '一覧へ戻る', media_converters_path %> <br />

app/views/partials/_form_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_media_converter_table.html.erb
<% dummy = MediaConverter.new %>
<table class="table table-bordered">
  <tr>
    <th><%= model_column_string dummy, "name" %></th>
    <th><%= model_column_string dummy, "manufacturer" %></th>
    <th>伝送損失(dB)</th>
    <% %w( fiber_type code_core_num price buying_price sale_price bandwidth desc).each do |name| %>
    <th><%= model_column_string dummy, name %></th>
    <% end %>
    <% if is_menu == true %>
    <th></th>
    <% end %>
  </tr>

<% @media_converters.each do |media_converter| %>
  <tr>
    <td><%= media_converter.name %></td>
    <td><%= media_converter.manufacturer %></td>
    <td><%= media_converter.trans_lost_from %> ~ <%= media_converter.trans_lost_to %></td>
    <td><%= media_converter.fiber_type %></td>
    <td><%= media_converter.code_core_num %></td>
    <td><%= number_to_currency media_converter.price, format: '%u %n', unit: '¥', precision: 0 %></td>
    <td><%= number_to_currency media_converter.buying_price, format: '%u %n', unit: '¥', precision: 0 %></td>
    <td><%= number_to_currency media_converter.sale_price, format: '%u %n', unit: '¥', precision: 0 %></td>
    <td><%= convert_size media_converter.bandwidth %></td>
    <td><%= convert_size media_converter.desc %></td>
    <% if is_menu == true %>
    <td>
      <a class="btn btn-primary" href="<%= url_for edit_media_converter_path(media_converter) %>">修正</a>
      <%= link_to '削除', media_converter, method: :delete, data: { confirm: '削除しますがよろしいですか?' }, class: "btn btn-danger" %>
    </td>
    <% end %>
  </tr>
<% end %>
</table>